### ISSUE TITLE
Terms of use acceptance

### ISSUE THREAD

**Issue by Xanatos00** [outadoc/linkindle#3]
It seems API need our manual consent about news TOU.
I  had already accept it, so I can't test for automation.

Il semblerait que l'API ait besoin que l'on accepte les nouvelles CGU de Linky, sinon le script ne marche pas.
J'ai déjà accepté, du coup je ne peut pas faire de tests pour automatiser l'accord des CGU.

**Comment by outadoc** [comment]
I added detection of new TOUs in commit 2bfac3b0 about ten days ago, and it should be working (it did for me!). I'm not too fond of the idea of accepting them automatically for legal reasons.

**Comment by Xanatos00** [comment]
Ooops, sorry.
