### ISSUE TITLE
connexion refusées

### ISSUE THREAD

**Issue by fturiot** [outadoc/linkindle#4]
la connexion est refusées . login et mots de passe sont bon en connexion manuelle.
y a t'il eu un changement chez enedis

**Comment by Azerane** [comment]
Idem, en fouillant un peu on voit qu'on récupère une erreur 302 sur le login

**Comment by outadoc** [comment]
Hello. J'ai une erreur à quasiment toutes les pages en essayant de me connecter manuellement à l'espace client Enedis donc je vais attendre un peu avant de paniquer 🤔

**Comment by Azerane** [comment]
On recoit aucun cookie après la request de login

**Comment by Azerane** [comment]
Hello. Une idée de ce qui ne fonctionne pas?

**Comment by outadoc** [comment]
Hello. J'ai une version qui remarche en local là ; on dirait qu'Enedis a ajouté du filtrage sur le user-agent. 🤷‍♂️ J'essaye de pusher un fix aujourd'hui.
